# Generated by Django 4.1.7 on 2023-02-22 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('numberPhone', models.CharField(max_length=100)),
                ('avatar', models.CharField(max_length=100)),
                ('sex', models.BooleanField(default=True)),
            ],
        ),
    ]
